version: '3'

services:
  database:
    build: ./.docker
    ports:
      - "5432:5432"
    volumes:
       - db-data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: "whizzes"
      POSTGRES_PASSWORD: "whizzes"
      POSTGRES_DB: "whizzes"

volumes:
  db-data: