version: '3'

services:
  api:
    build: ./docker/api
    ports:
      - '3000:3000'
    volumes:
      - "$PWD:/app"
    env_file:
      - .env

  database:
    build: ./docker/database
    ports:
      - '5432:5432'
    volumes:
      - teatime-database:/var/lib/postgresql/data
    env_file:
      - .env

volumes:
  teatime-database:
